objects/Marks__c.object
<CustomObject>
    <description>MArks obtained by students in a subject</description>
    <fields>
        <fullName>Marks_Obtained__c</fullName>
        <label>Marks Obtained</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Marks__c</fullName>
        <label>Maximum Marks</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Marks</relationshipLabel>
        <relationshipName>Marks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subject_Name__c</fullName>
        <inlineHelpText>Name of the subject</inlineHelpText>
        <label>Subject Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Marks</label>
    <nameField>
        <displayFormat>MarksRec-{0000000}</displayFormat>
        <label>Marks Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StudentReportController.cls
public class StudentReportController {
public Map<String,List<Marks__c>> mapOfMarks{get;set;}

public StudentReportController(){
mapOfMarks = new Map<String,List<Marks__c>>();
for(Marks__c m : [SELECT Id,Marks_Obtained__c,Maximum_Marks__c,Subject_Name__c,Student__r.Name FROM Marks__c]){
List<Marks__c> l = mapOfMarks.get(m.Student__r.Name);
if(l==null)
l = new List<Marks__c>();
l.add(m);
mapOfMarks.put(m.Student__r.Name,l);
}
}
}